project_id = "zwtnoiuextlrhengwtrk"

[functions.create-agent]
verify_jwt = false

[functions.update-agent]
verify_jwt = false

[functions.assign-agent]
verify_jwt = false

[functions.outbound-call]
verify_jwt = false
