// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zwtnoiuextlrhengwtrk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp3dG5vaXVleHRscmhlbmd3dHJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3MzQ4NjMsImV4cCI6MjA3NDMxMDg2M30.m-m27zsI2C_fnw2qPmTR12ZcGNYxq6cEma2dAkQBPDk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});