// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ubqcxxfynhnwhvtogkvx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVicWN4eGZ5bmhud2h2dG9na3Z4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxNTc5NTcsImV4cCI6MjA3NDczMzk1N30.VrKgsCA7Odn838DzwJRptkSou1F6w9el0euEXQBgwdE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});